import { PdfJobStatusEnum } from '@common/interfaces/analysis-result.interface';
import { BloodTestData } from '@common/interfaces/blood-test-data.interface';

/* eslint-disable no-useless-escape */
export const REQUEST_USER_KEY = 'user';
export const COOKIE_MAX_AGE = 1000 * 60 * 60 * 24;
export const COOKIE_SECURE = false;
export const ISSUER = 'https://www.linkedin.com/oauth';
export const AUTHORIZATION_URL =
  'https://www.linkedin.com/oauth/v2/authorization';
export const TOKEN_URL = 'https://www.linkedin.com/oauth/v2/accessToken';
export const USER_INFO_URL = 'https://api.linkedin.com/v2/userinfo';
export const BASE64_PATTERN =
  /^data:(image\/(png|jpg|jpeg)|application\/pdf);base64,/i;

export const SUPPORTED_LANGUAGES = ['en', 'uk', 'pl'];

export const CATEGORIES = [
  'patientInfo',
  'lipids',
  'bloodAll',
  'kidneyFunction',
  'liverFunction',
];

export const markers = [
  // ========== ENGLISH ==========

  // Blood Count (Complete Blood Count - CBC)
  {
    key: 'wbc',
    lang: 'en',
    pattern: 'WBC[:\\s]*([\\d.,]+)|Leukocytes[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'White Blood Cells,Leukocytes,WBC',
    unit: '10^9/L',
    min: 4.9,
    max: 10.7,
  },
  {
    key: 'rbc',
    lang: 'en',
    pattern: 'RBC[:\\s]*([\\d.,]+)|Erythrocytes[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Red Blood Cells,Erythrocytes,RBC',
    unit: '10^12/L',
    min: 4.5,
    max: 6.7,
  },
  {
    key: 'hemoglobin',
    lang: 'en',
    pattern: 'Hemoglobin[:\\s]*([\\d.,]+)|HGB[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Hemoglobin,HGB,Hb',
    unit: 'g/L',
    min: 130.0,
    max: 160.0,
  },
  {
    key: 'hematocrit',
    lang: 'en',
    pattern: 'Hematocrit[:\\s]*([\\d.,]+)|HCT[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Hematocrit,HCT',
    unit: '%',
    min: 35.54,
    max: 54.0,
  },
  {
    key: 'mcv',
    lang: 'en',
    pattern: 'MCV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Mean Corpuscular Volume,MCV',
    unit: 'fL',
    min: 76.96,
    max: 96.0,
  },
  {
    key: 'mch',
    lang: 'en',
    pattern: 'MCH[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Mean Corpuscular Hemoglobin,MCH',
    unit: 'pg',
    min: 27.33,
    max: 33.0,
  },
  {
    key: 'mchc',
    lang: 'en',
    pattern: 'MCHC[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Mean Corpuscular Hemoglobin Concentration,MCHC',
    unit: 'g/L',
    min: 32.36,
    max: 36.0,
  },
  {
    key: 'plt',
    lang: 'en',
    pattern: 'Platelets[:\\s]*([\\d.,]+)|PLT[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Platelets,Thrombocytes,PLT',
    unit: '10^9/L',
    min: 180.0,
    max: 360.0,
  },
  {
    key: 'rdw_sd',
    lang: 'en',
    pattern: 'RDW[\\s-]*SD[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Red Cell Distribution Width SD,RDW-SD',
    unit: 'fL',
    min: 35.46,
    max: 46.0,
  },
  {
    key: 'rdw_cv',
    lang: 'en',
    pattern: 'RDW[\\s-]*CV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Red Cell Distribution Width CV,RDW-CV',
    unit: '%',
    min: 12.0,
    max: 15.0,
  },
  {
    key: 'pdw',
    lang: 'en',
    pattern: 'PDW[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Platelet Distribution Width,PDW',
    unit: '%',
    min: 10.0,
    max: 20.0,
  },
  {
    key: 'mpv',
    lang: 'en',
    pattern: 'MPV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Mean Platelet Volume,MPV',
    unit: 'fL',
    min: 6.13,
    max: 13.0,
  },
  {
    key: 'p_lcr',
    lang: 'en',
    pattern: 'P[\\s-]*LCR[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Platelet Large Cell Ratio,P-LCR',
    unit: '%',
    min: 0.1,
    max: 65.0,
  },

  // White Blood Cell Differential
  {
    key: 'neutrophils_abs',
    lang: 'en',
    pattern: 'Neutrophils[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Neutrophils Absolute',
    unit: '10^9/L',
    min: 1.78,
    max: 5.38,
  },
  {
    key: 'lymphocytes_abs',
    lang: 'en',
    pattern: 'Lymphocytes[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Lymphocytes Absolute',
    unit: '10^9/L',
    min: 1.9,
    max: 3.7,
  },
  {
    key: 'monocytes_abs',
    lang: 'en',
    pattern: 'Monocytes[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Monocytes Absolute',
    unit: '10^9/L',
    min: 1.32,
    max: 3.57,
  },
  {
    key: 'eosinophils_abs',
    lang: 'en',
    pattern: 'Eosinophils[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Eosinophils Absolute',
    unit: '10^9/L',
    min: 0.5,
    max: 5.0,
  },
  {
    key: 'basophils_abs',
    lang: 'en',
    pattern: 'Basophils[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Basophils Absolute',
    unit: '10^9/L',
    min: 0.04,
    max: 0.54,
  },

  // ESR
  {
    key: 'esr',
    lang: 'en',
    pattern: 'ESR[:\\s]*([\\d.,]+)|Sedimentation\\s+rate[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Erythrocyte Sedimentation Rate,ESR,SOE',
    unit: 'mm/h',
    min: 0.0,
    max: 20.0,
  },

  // Lipids
  {
    key: 'triglycerides',
    lang: 'en',
    pattern: 'Triglycerides[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Triglycerides,TG,TRIG',
    unit: 'mmol/L',
    min: 0.0,
    max: 2.26,
  },
  {
    key: 'cholesterol',
    lang: 'en',
    pattern: 'Cholesterol[:\\s]*(?:total)?[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Total Cholesterol,CHOL',
    unit: 'mmol/L',
    min: 0.0,
    max: 5.2,
  },
  {
    key: 'hdl',
    lang: 'en',
    pattern: 'HDL[:\\s-]*(?:Cholesterol)?[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'HDL Cholesterol,HDL-C,HDL',
    unit: 'mmol/L',
    min: 0.9,
    max: 1.45,
  },
  {
    key: 'ldl',
    lang: 'en',
    pattern: 'LDL[:\\s-]*(?:Cholesterol)?[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'LDL Cholesterol,LDL-C,LDL',
    unit: 'mmol/L',
    min: 0.0,
    max: 3.36,
  },
  {
    key: 'vldl',
    lang: 'en',
    pattern: 'VLDL[:\\s-]*(?:Cholesterol)?[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'VLDL Cholesterol,VLDL-C,VLDL',
    unit: 'mmol/L',
    min: 0.26,
    max: 1.0,
  },
  {
    key: 'atherogenic_coefficient',
    lang: 'en',
    pattern: 'Atherogenic\\s+coefficient[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Atherogenic Coefficient,Atherogenic Index',
    unit: '',
    min: 0.0,
    max: 3.0,
  },

  // Kidney Function
  {
    key: 'urea',
    lang: 'en',
    pattern: 'Urea[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Urea,BUN',
    unit: 'mmol/L',
    min: 2.76,
    max: 8.07,
  },
  {
    key: 'uricAcid',
    lang: 'en',
    pattern: 'Uric\\s+[Aa]cid[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Uric Acid,UA,Urate',
    unit: 'mmol/L',
    min: 202.3,
    max: 416.5,
  },
  {
    key: 'creatinine',
    lang: 'en',
    pattern: 'Creatinine[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Creatinine,CREAT',
    unit: 'μmol/L',
    min: 62.0,
    max: 106.0,
  },
  {
    key: 'creatinine_block',
    lang: 'en',
    pattern: 'Creatinine\\s+block[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Creatinine Block',
    unit: 'μmol/L',
    min: 66.0,
    max: 87.0,
  },

  // Liver Function
  {
    key: 'totalBilirubin',
    lang: 'en',
    pattern: 'Total\\s+[Bb]ilirubin[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Total Bilirubin,TBIL',
    unit: 'μmol/L',
    min: 0.0,
    max: 21.0,
  },
  {
    key: 'directBilirubin',
    lang: 'en',
    pattern: 'Direct\\s+[Bb]ilirubin[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Direct Bilirubin,DBIL,Conjugated Bilirubin',
    unit: 'μmol/L',
    min: 0.0,
    max: 5.0,
  },
  {
    key: 'indirectBilirubin',
    lang: 'en',
    pattern: 'Indirect\\s+[Bb]ilirubin[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Indirect Bilirubin,Unconjugated Bilirubin',
    unit: 'μmol/L',
    min: 0.0,
    max: 16.39,
  },
  {
    key: 'alt',
    lang: 'en',
    pattern:
      'ALT[:\\s]*([\\d.,]+)|Alanine\\s+aminotransferase[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Alanine Aminotransferase,ALT,ALAT,GPT',
    unit: 'U/L',
    min: 0.0,
    max: 41.0,
  },
  {
    key: 'ast',
    lang: 'en',
    pattern:
      'AST[:\\s]*([\\d.,]+)|Aspartate\\s+aminotransferase[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Aspartate Aminotransferase,AST,ASAT,GOT',
    unit: 'U/L',
    min: 0.0,
    max: 40.0,
  },
  {
    key: 'ggt',
    lang: 'en',
    pattern:
      'GGT[:\\s]*([\\d.,]+)|Gamma[\\s-]*glutamyl\\s+transferase[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Gamma-Glutamyl Transferase,GGT,Gamma-GT',
    unit: 'U/L',
    min: 8.61,
    max: 61.0,
  },
  {
    key: 'alp',
    lang: 'en',
    pattern: 'ALP[:\\s]*([\\d.,]+)|Alkaline\\s+phosphatase[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Alkaline Phosphatase,ALP',
    unit: 'U/L',
    min: 40.0,
    max: 129.0,
  },
  {
    key: 'albumin',
    lang: 'en',
    pattern: 'Albumin[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Albumin,ALB',
    unit: 'g/L',
    min: 35.0,
    max: 52.0,
  },

  // Metabolism
  {
    key: 'glucose',
    lang: 'en',
    pattern: 'Glucose[:\\s]*([\\d.,]+)',
    cat: 'metabolism',
    names: 'Glucose,GLU,Blood Sugar',
    unit: 'mmol/L',
    min: 4.11,
    max: 5.89,
  },

  // ========== UKRAINIAN ==========

  // Blood Count (Повний аналіз крові)
  {
    key: 'wbc',
    lang: 'uk',
    pattern: 'Лейкоцити[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: "Білі кров'яні тільця,Лейкоцити",
    unit: '10^9/л',
    min: 4.9,
    max: 10.7,
  },
  {
    key: 'rbc',
    lang: 'uk',
    pattern: 'Еритроцити[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: "Червоні кров'яні тільця,Еритроцити",
    unit: '10^12/л',
    min: 4.5,
    max: 6.7,
  },
  {
    key: 'hemoglobin',
    lang: 'uk',
    pattern: 'Гемоглобін[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Гемоглобін,HGB',
    unit: 'г/л',
    min: 130.0,
    max: 160.0,
  },
  {
    key: 'hematocrit',
    lang: 'uk',
    pattern: 'Гематокрит[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Гематокрит,HCT',
    unit: '%',
    min: 35.54,
    max: 54.0,
  },
  {
    key: 'mcv',
    lang: 'uk',
    pattern: 'MCV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: "Середній об'єм еритроцита,MCV",
    unit: 'фл',
    min: 76.96,
    max: 96.0,
  },
  {
    key: 'mch',
    lang: 'uk',
    pattern: 'MCH[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Середній вміст гемоглобіну в еритроциті,MCH',
    unit: 'пг',
    min: 27.33,
    max: 33.0,
  },
  {
    key: 'mchc',
    lang: 'uk',
    pattern: 'MCHC[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Середня концентрація гемоглобіну в еритроциті,MCHC',
    unit: 'г/л',
    min: 32.36,
    max: 36.0,
  },
  {
    key: 'plt',
    lang: 'uk',
    pattern: 'Тромбоцити[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: "Кров'яні пластинки,Тромбоцити",
    unit: '10^9/л',
    min: 180.0,
    max: 360.0,
  },
  {
    key: 'rdw_sd',
    lang: 'uk',
    pattern: 'RDW[\\s-]*SD[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Ширина розподілу еритроцитів SD,RDW-SD',
    unit: 'фл',
    min: 35.46,
    max: 46.0,
  },
  {
    key: 'rdw_cv',
    lang: 'uk',
    pattern: 'RDW[\\s-]*CV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Ширина розподілу еритроцитів CV,RDW-CV',
    unit: '%',
    min: 12.0,
    max: 15.0,
  },
  {
    key: 'pdw',
    lang: 'uk',
    pattern: 'PDW[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Ширина розподілу тромбоцитів,PDW',
    unit: '%',
    min: 10.0,
    max: 20.0,
  },
  {
    key: 'mpv',
    lang: 'uk',
    pattern: 'MPV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: "Середній об'єм тромбоцитів,MPV",
    unit: 'фл',
    min: 6.13,
    max: 13.0,
  },
  {
    key: 'p_lcr',
    lang: 'uk',
    pattern: 'P[\\s-]*LCR[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Коефіцієнт великих тромбоцитів,P-LCR',
    unit: '%',
    min: 0.1,
    max: 65.0,
  },

  // Лейкоцитарна формула
  {
    key: 'neutrophils_abs',
    lang: 'uk',
    pattern: 'Нейтрофіли[:\\s]*\\(абс[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Нейтрофіли абсолютні',
    unit: '10^9/л',
    min: 1.78,
    max: 5.38,
  },
  {
    key: 'lymphocytes_abs',
    lang: 'uk',
    pattern: 'Лімфоцити[:\\s]*\\(абс[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Лімфоцити абсолютні',
    unit: '10^9/л',
    min: 1.9,
    max: 3.7,
  },
  {
    key: 'monocytes_abs',
    lang: 'uk',
    pattern: 'Моноцити[:\\s]*\\(абс[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Моноцити абсолютні',
    unit: '10^9/л',
    min: 1.32,
    max: 3.57,
  },
  {
    key: 'eosinophils_abs',
    lang: 'uk',
    pattern: 'Еозинофіли[:\\s]*\\(абс[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Еозинофіли абсолютні',
    unit: '10^9/л',
    min: 0.5,
    max: 5.0,
  },
  {
    key: 'basophils_abs',
    lang: 'uk',
    pattern: 'Базофіли[:\\s]*\\(абс[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Базофіли абсолютні',
    unit: '10^9/л',
    min: 0.04,
    max: 0.54,
  },

  // ШОЕ
  {
    key: 'esr',
    lang: 'uk',
    pattern: 'ШОЕ[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Швидкість осідання еритроцитів,ШОЕ',
    unit: 'мм/год',
    min: 0.0,
    max: 20.0,
  },

  // Ліпіди
  {
    key: 'triglycerides',
    lang: 'uk',
    pattern: 'Тригліцериди[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Тригліцериди,ТГ',
    unit: 'ммоль/л',
    min: 0.0,
    max: 2.26,
  },
  {
    key: 'cholesterol',
    lang: 'uk',
    pattern: 'Холестерин[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Загальний холестерин',
    unit: 'ммоль/л',
    min: 0.0,
    max: 5.2,
  },
  {
    key: 'hdl',
    lang: 'uk',
    pattern: 'HDL[:\\s]*([\\d.,]+)|ЛПВЩ[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Ліпопротеїни високої щільності,ЛПВЩ,HDL',
    unit: 'ммоль/л',
    min: 0.9,
    max: 1.45,
  },
  {
    key: 'ldl',
    lang: 'uk',
    pattern: 'LDL[:\\s]*([\\d.,]+)|ЛПНЩ[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Ліпопротеїни низької щільності,ЛПНЩ,LDL',
    unit: 'ммоль/л',
    min: 0.0,
    max: 3.36,
  },
  {
    key: 'vldl',
    lang: 'uk',
    pattern: 'VLDL[:\\s]*([\\d.,]+)|ЛПДНЩ[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Ліпопротеїни дуже низької щільності,ЛПДНЩ,VLDL',
    unit: 'ммоль/л',
    min: 0.26,
    max: 1.0,
  },
  {
    key: 'atherogenic_coefficient',
    lang: 'uk',
    pattern: 'Коефіцієнт\\s+атерогенності[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Коефіцієнт атерогенності',
    unit: '',
    min: 0.0,
    max: 3.0,
  },

  // Нирки
  {
    key: 'urea',
    lang: 'uk',
    pattern: 'Сечовина[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Сечовина',
    unit: 'ммоль/л',
    min: 2.76,
    max: 8.07,
  },
  {
    key: 'uricAcid',
    lang: 'uk',
    pattern: 'Сечова\\s+кислота[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Сечова кислота',
    unit: 'ммоль/л',
    min: 202.3,
    max: 416.5,
  },
  {
    key: 'creatinine',
    lang: 'uk',
    pattern: 'Креатинін[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Креатинін',
    unit: 'мкмоль/л',
    min: 62.0,
    max: 106.0,
  },
  {
    key: 'creatinine_block',
    lang: 'uk',
    pattern: 'Креатиніновий\\s+блок[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Креатиніновий блок',
    unit: 'мкмоль/л',
    min: 66.0,
    max: 87.0,
  },

  // Печінка
  {
    key: 'totalBilirubin',
    lang: 'uk',
    pattern:
      'Загальний\\s+білірубін[:\\s]*([\\d.,]+)|Білірубін\\s+загальний[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Загальний білірубін,Білірубін загальний',
    unit: 'мкмоль/л',
    min: 0.0,
    max: 21.0,
  },
  {
    key: 'directBilirubin',
    lang: 'uk',
    pattern:
      'Прямий\\s+білірубін[:\\s]*([\\d.,]+)|Білірубін\\s+прямий[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Прямий білірубін,Білірубін прямий',
    unit: 'мкмоль/л',
    min: 0.0,
    max: 5.0,
  },
  {
    key: 'indirectBilirubin',
    lang: 'uk',
    pattern:
      'Непрямий\\s+білірубін[:\\s]*([\\d.,]+)|Білірубін\\s+непрямий[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Непрямий білірубін,Білірубін непрямий',
    unit: 'мкмоль/л',
    min: 0.0,
    max: 16.39,
  },
  {
    key: 'alt',
    lang: 'uk',
    pattern: 'АЛТ[:\\s]*([\\d.,]+)|Аланінамінотрансфераза[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Аланінамінотрансфераза,АЛТ,АЛАТ',
    unit: 'Од/л',
    min: 0.0,
    max: 41.0,
  },
  {
    key: 'ast',
    lang: 'uk',
    pattern: 'АСТ[:\\s]*([\\d.,]+)|Аспартатамінотрансфераза[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Аспартатамінотрансфераза,АСТ,АСАТ',
    unit: 'Од/л',
    min: 0.0,
    max: 40.0,
  },
  {
    key: 'ggt',
    lang: 'uk',
    pattern:
      'ГГТ[:\\s]*([\\d.,]+)|Г[\\s-]*глутамілтрансфераза[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Гамма-глутамілтрансфераза,ГГТ,Г-глутамілтрансфераза',
    unit: 'Од/л',
    min: 8.61,
    max: 61.0,
  },
  {
    key: 'alp',
    lang: 'uk',
    pattern: 'ЛФ[:\\s]*([\\d.,]+)|Лужна\\s+фосфатаза[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Лужна фосфатаза,ЛФ',
    unit: 'Од/л',
    min: 40.0,
    max: 129.0,
  },
  {
    key: 'albumin',
    lang: 'uk',
    pattern: 'Альбумін[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Альбумін',
    unit: 'г/л',
    min: 35.0,
    max: 52.0,
  },

  // Метаболізм
  {
    key: 'glucose',
    lang: 'uk',
    pattern: 'Глюкоза[:\\s]*([\\d.,]+)',
    cat: 'metabolism',
    names: 'Глюкоза,Цукор крові',
    unit: 'ммоль/л',
    min: 4.11,
    max: 5.89,
  },

  // ========== POLISH ==========

  // Morfologia (Complete Blood Count)
  {
    key: 'wbc',
    lang: 'pl',
    pattern: 'Leukocyty[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Białe krwinki,Leukocyty',
    unit: '10^9/l',
    min: 4.9,
    max: 10.7,
  },
  {
    key: 'rbc',
    lang: 'pl',
    pattern: 'Erytrocyty[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Czerwone krwinki,Erytrocyty',
    unit: '10^12/l',
    min: 4.5,
    max: 6.7,
  },
  {
    key: 'hemoglobin',
    lang: 'pl',
    pattern: 'Hemoglobina[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Hemoglobina,HGB',
    unit: 'g/l',
    min: 130.0,
    max: 160.0,
  },
  {
    key: 'hematocrit',
    lang: 'pl',
    pattern: 'Hematokryt[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Hematokryt,HCT',
    unit: '%',
    min: 35.54,
    max: 54.0,
  },
  {
    key: 'mcv',
    lang: 'pl',
    pattern: 'MCV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Średnia objętość krwinki,MCV',
    unit: 'fL',
    min: 76.96,
    max: 96.0,
  },
  {
    key: 'mch',
    lang: 'pl',
    pattern: 'MCH[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Średnia masa hemoglobiny,MCH',
    unit: 'pg',
    min: 27.33,
    max: 33.0,
  },
  {
    key: 'mchc',
    lang: 'pl',
    pattern: 'MCHC[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Średnie stężenie hemoglobiny,MCHC',
    unit: 'g/l',
    min: 32.36,
    max: 36.0,
  },
  {
    key: 'plt',
    lang: 'pl',
    pattern: 'Płytki\\s+krwi[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Płytki krwi,Trombocyty',
    unit: '10^9/l',
    min: 180.0,
    max: 360.0,
  },
  {
    key: 'rdw_sd',
    lang: 'pl',
    pattern: 'RDW[\\s-]*SD[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Szerokość rozkładu erytrocytów SD,RDW-SD',
    unit: 'fL',
    min: 35.46,
    max: 46.0,
  },
  {
    key: 'rdw_cv',
    lang: 'pl',
    pattern: 'RDW[\\s-]*CV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Szerokość rozkładu erytrocytów CV,RDW-CV',
    unit: '%',
    min: 12.0,
    max: 15.0,
  },
  {
    key: 'pdw',
    lang: 'pl',
    pattern: 'PDW[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Szerokość rozkładu płytek,PDW',
    unit: '%',
    min: 10.0,
    max: 20.0,
  },
  {
    key: 'mpv',
    lang: 'pl',
    pattern: 'MPV[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Średnia objętość płytek,MPV',
    unit: 'fL',
    min: 6.13,
    max: 13.0,
  },
  {
    key: 'p_lcr',
    lang: 'pl',
    pattern: 'P[\\s-]*LCR[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Współczynnik dużych płytek,P-LCR',
    unit: '%',
    min: 0.1,
    max: 65.0,
  },

  // Rozmaz krwi
  {
    key: 'neutrophils_abs',
    lang: 'pl',
    pattern: 'Neutrofile[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Neutrofile bezwzględne',
    unit: '10^9/l',
    min: 1.78,
    max: 5.38,
  },
  {
    key: 'lymphocytes_abs',
    lang: 'pl',
    pattern: 'Limfocyty[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Limfocyty bezwzględne',
    unit: '10^9/l',
    min: 1.9,
    max: 3.7,
  },
  {
    key: 'monocytes_abs',
    lang: 'pl',
    pattern: 'Monocyty[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Monocyty bezwzględne',
    unit: '10^9/l',
    min: 1.32,
    max: 3.57,
  },
  {
    key: 'eosinophils_abs',
    lang: 'pl',
    pattern: 'Eozynofile[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Eozynofile bezwzględne',
    unit: '10^9/l',
    min: 0.5,
    max: 5.0,
  },
  {
    key: 'basophils_abs',
    lang: 'pl',
    pattern: 'Bazofile[:\\s]*\\(abs[:\\s.]*\\)[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Bazofile bezwzględne',
    unit: '10^9/l',
    min: 0.04,
    max: 0.54,
  },

  // OB
  {
    key: 'esr',
    lang: 'pl',
    pattern: 'OB[:\\s]*([\\d.,]+)',
    cat: 'bloodAll',
    names: 'Odczyn opadania krwinek,OB',
    unit: 'mm/h',
    min: 0.0,
    max: 20.0,
  },

  // Lipidy
  {
    key: 'triglycerides',
    lang: 'pl',
    pattern: 'Trójglicerydy[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Trójglicerydy,TG',
    unit: 'mmol/l',
    min: 0.0,
    max: 2.26,
  },
  {
    key: 'cholesterol',
    lang: 'pl',
    pattern: 'Cholesterol[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Cholesterol całkowity',
    unit: 'mmol/l',
    min: 0.0,
    max: 5.2,
  },
  {
    key: 'hdl',
    lang: 'pl',
    pattern: 'HDL[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Cholesterol HDL,HDL-C',
    unit: 'mmol/l',
    min: 0.9,
    max: 1.45,
  },
  {
    key: 'ldl',
    lang: 'pl',
    pattern: 'LDL[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Cholesterol LDL,LDL-C',
    unit: 'mmol/l',
    min: 0.0,
    max: 3.36,
  },
  {
    key: 'vldl',
    lang: 'pl',
    pattern: 'VLDL[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Cholesterol VLDL,VLDL-C',
    unit: 'mmol/l',
    min: 0.26,
    max: 1.0,
  },
  {
    key: 'atherogenic_coefficient',
    lang: 'pl',
    pattern: 'Współczynnik\\s+miażdżycowy[:\\s]*([\\d.,]+)',
    cat: 'lipids',
    names: 'Współczynnik miażdżycowy',
    unit: '',
    min: 0.0,
    max: 3.0,
  },

  // Nerki
  {
    key: 'urea',
    lang: 'pl',
    pattern: 'Mocznik[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Mocznik',
    unit: 'mmol/l',
    min: 2.76,
    max: 8.07,
  },
  {
    key: 'uricAcid',
    lang: 'pl',
    pattern: 'Kwas\\s+moczowy[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Kwas moczowy,UA',
    unit: 'mmol/l',
    min: 202.3,
    max: 416.5,
  },
  {
    key: 'creatinine',
    lang: 'pl',
    pattern: 'Kreatynina[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Kreatynina,CREAT',
    unit: 'μmol/l',
    min: 62.0,
    max: 106.0,
  },
  {
    key: 'creatinine_block',
    lang: 'pl',
    pattern: 'Blok\\s+kreatyninowy[:\\s]*([\\d.,]+)',
    cat: 'kidneyFunction',
    names: 'Blok kreatyninowy',
    unit: 'μmol/l',
    min: 66.0,
    max: 87.0,
  },

  // Wątroba
  {
    key: 'totalBilirubin',
    lang: 'pl',
    pattern: 'Bilirubina\\s+całkowita[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Bilirubina całkowita',
    unit: 'μmol/l',
    min: 0.0,
    max: 21.0,
  },
  {
    key: 'directBilirubin',
    lang: 'pl',
    pattern: 'Bilirubina\\s+bezpośrednia[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Bilirubina bezpośrednia,Bilirubina sprzężona',
    unit: 'μmol/l',
    min: 0.0,
    max: 5.0,
  },
  {
    key: 'indirectBilirubin',
    lang: 'pl',
    pattern: 'Bilirubina\\s+pośrednia[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Bilirubina pośrednia,Bilirubina niesprzężona',
    unit: 'μmol/l',
    min: 0.0,
    max: 16.39,
  },
  {
    key: 'alt',
    lang: 'pl',
    pattern:
      'ALT[:\\s]*([\\d.,]+)|Aminotransferaza\\s+alaninowa[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Aminotransferaza alaninowa,ALT,ALAT',
    unit: 'U/l',
    min: 0.0,
    max: 41.0,
  },
  {
    key: 'ast',
    lang: 'pl',
    pattern:
      'AST[:\\s]*([\\d.,]+)|Aminotransferaza\\s+asparaginianowa[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Aminotransferaza asparaginianowa,AST,ASAT',
    unit: 'U/l',
    min: 0.0,
    max: 40.0,
  },
  {
    key: 'ggt',
    lang: 'pl',
    pattern:
      'GGT[:\\s]*([\\d.,]+)|Gamma[\\s-]*glutamylotransferaza[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Gamma-glutamylotransferaza,GGT,GGTP',
    unit: 'U/l',
    min: 8.61,
    max: 61.0,
  },
  {
    key: 'alp',
    lang: 'pl',
    pattern: 'ALP[:\\s]*([\\d.,]+)|Fosfataza\\s+alkaliczna[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Fosfataza alkaliczna,ALP',
    unit: 'U/l',
    min: 40.0,
    max: 129.0,
  },
  {
    key: 'albumin',
    lang: 'pl',
    pattern: 'Albumina[:\\s]*([\\d.,]+)',
    cat: 'liverFunction',
    names: 'Albumina,ALB',
    unit: 'g/l',
    min: 35.0,
    max: 52.0,
  },

  // Metabolizm
  {
    key: 'glucose',
    lang: 'pl',
    pattern: 'Glukoza[:\\s]*([\\d.,]+)',
    cat: 'metabolism',
    names: 'Glukoza,Cukier',
    unit: 'mmol/l',
    min: 4.11,
    max: 5.89,
  },
];

export function getValidationPrompt(values: BloodTestData): string {
  return `You are a medical data validation assistant.

Your task: Determine if the provided array represents actual blood test results extracted via OCR.

IMPORTANT CONTEXT:
- This data was extracted from a scanned blood test document using OCR
- Some values MAY be outside normal ranges (that's medically possible and expected)
- Some values MAY have OCR extraction errors (e.g., misread digits)
- Field names use technical IDs (e.g., "hemoglobin", "glucose", "ldl")
- Reference ranges are included for each marker

Criteria for a VALID blood test:
1. Contains at least 3 medical parameters with numeric values
2. Has proper medical terminology (hemoglobin, glucose, cholesterol, creatinine, etc.)
3. Includes units typical for lab tests (g/L, mmol/L, %, etc.)
4. Has reference ranges (referenceMin/referenceMax)
5. Values are numeric (even if some seem unusual due to OCR errors)

Criteria for INVALID (reject):
- Random data with no medical context
- Only 1-2 parameters
- No recognizable medical marker names
- Missing units entirely
- Values are clearly text/gibberish, not numbers

NOTE: Do NOT reject based on:
- Values being outside normal ranges (patients can have abnormal results)
- Potential OCR errors in numbers (e.g., "235" instead of "2.35")
- Technical naming conventions (snake_case IDs are acceptable)

Data to validate:
${JSON.stringify(values, null, 2)}

Analyze this data and respond ONLY with valid JSON (no markdown, no code blocks):
{
  "isBloodTest": boolean,
  "reason": "brief explanation focusing on structure and medical terminology, not value ranges",
  "confidence": "low" | "medium" | "high"
}`;
}

export const AI_MODEL: string = 'gpt-4o';
export const AI_TEMPERATURE: number = 0.3;
export const MAX_VALIDATION_TOKENS: number = 4000;
export const PDF_DIR_NAME: string = 'generated-pdfs';
export const PDF_EXPIRY_MS: number = 15 * 60 * 1000;
export const JOB_ID_PATTERN: RegExp = /^pdf_\d+_[a-z0-9]+$/;

export interface PdfCacheEntry {
  buffer: Buffer;
  createdAt: Date;
  status: PdfJobStatusEnum;
  error?: string;
}

export const ERROR_MESSAGES = {
  PDF_JOB_NOT_FOUND: 'PDF job not found',
  PDF_STILL_GENERATING: 'PDF is still being generated',
  PDF_GENERATION_FAILED: 'PDF generation failed',
  PDF_NOT_FOUND_OR_EXPIRED: 'PDF file not found or expired',
  INVALID_JOB_ID: 'Invalid job ID format',
} as const;

export const PDF_HEADERS = {
  CONTENT_TYPE: 'application/pdf',
  FILENAME: 'health-report.pdf',
} as const;
